@startuml
title Récupération profil utilisateur (Frontend)
autonumber

actor "Utilisateur" as User
participant "UI" as UI
participant "Backend" as BE
database "Base de données" as DB

User -> UI : Clique sur l'icone "Profile"
UI -> BE : GET /login (user_cred)

UI --> UI : supprime JWT du localStorage

@enduml